### ISSUE TITLE
tree-sitter-php seems to ignore __DIR__

### ISSUE THREAD

**Issue by etu** [tree-sitter/tree-sitter-php#147]
I've just started to try out tree-sitter, one thing that I noticed straight away is that it seems to ignore `__DIR__`, a bunch of other of constants (like `__FILE__`) is handled much better.

See screenshot: 
![image](https://user-images.githubusercontent.com/461970/186482073-8a5f4ee7-ecf3-4174-916c-f27d948223f5.png)

I did find #144, however that was a while ago and this is more specific to just `__DIR__` :slightly_smiling_face: 

EDIT:
Code:
```php
<?php

echo(__FILE__);
echo(__DIR__);
echo(__FUNCTION__);
echo(__METHOD__);
echo(__CLASS__);
echo(__TRAIT__);
echo(__NAMESPACE__);
echo(__LINE__);
```

Debug:
```
program:
  php_tag:
  echo_statement:
    parenthesized_expression:
      name:
  echo_statement:
    parenthesized_expression:
      name:
  echo_statement:
    parenthesized_expression:
      name:
  echo_statement:
    parenthesized_expression:
      name:
  echo_statement:
    parenthesized_expression:
      name:
  echo_statement:
    parenthesized_expression:
      name:
  echo_statement:
    parenthesized_expression:
      name:
  echo_statement:
    parenthesized_expression:
      name:
```

And now I'm realizing that they are all the same... so... it's something weird with something else... like in the emacs mode maybe that displays this... or something maybe that conflicts with php-mode... or something... I'm not sure. The parser does this fine.
