### ISSUE TITLE
function names ending with the word `_function` is not parsed correctly

### ISSUE THREAD

**Issue by etu** [tree-sitter/tree-sitter-php#148]
PHP code:
```php
<?php

function foobar_function(): void
{
    echo 'foobar';
    echo "foobar";
}

foobar_function();
```

Debug data:
```
program:
  php_tag:
  function_definition:
    name:
    formal_parameters:
    union_type:
      primitive_type:
    compound_statement:
      echo_statement:
        string:
          string_value:
      echo_statement:
        encapsed_string:
          string_value:
  expression_statement:
    function_call_expression:
      name:
      arguments:
```

![image](https://user-images.githubusercontent.com/461970/186481420-91375030-169e-4bb4-81e9-3f258cdd8185.png)

It doesn't seem to be an issue for methods:
```php
<?php

class Foobar {
    public function __construct()
    {
        $this->foobar_function();
    }

    public function foobar_function(): void
    {
        echo 'foobar';
        echo "foobar";
    }
}
```

Debug:
```
program:
  php_tag:
  class_declaration:
    name:
    declaration_list:
      method_declaration:
        visibility_modifier:
        name:
        formal_parameters:
        compound_statement:
          expression_statement:
            member_call_expression:
              variable_name:
                name:
              name:
              arguments:
      method_declaration:
        visibility_modifier:
        name:
        formal_parameters:
        union_type:
          primitive_type:
        compound_statement:
          echo_statement:
            string:
              string_value:
          echo_statement:
            encapsed_string:
              string_value:
```

I found this due to usage of this function: https://www.php.net/manual/en/function.register-shutdown-function.php
